### ISSUE TITLE
Best way to set connection options

### ISSUE THREAD

**Issue by joshystuart** [zoopcommerce/shard#35]
Hey @superdweebie,

I realise you set Mongo connection options here https://github.com/zoopcommerce/shard/blob/master/lib/Zoop/Shard/ODMCore/DevDocumentManagerFactory.php#L77. However, what's the best way of passing in those options? 

I know in the shard manifest config there's a way to pass in the factory. But is there any way to pass arguments to the factory?

``` php
'service_manager_config' => [
                'factories' => [
                    'modelmanager' => 'Zoop\Legacy\Store\DocumentManagerFactory'
                ]
            ]
```

**Comment by joshystuart** [comment]
I think I have an idea; I create a `ServiceManager` containing a config class, and pass that into the `Manifest`?

**Comment by joshystuart** [comment]
I ended up hacking something together:

``` php
 'service_manager_config' => [
                'factories' => [
                    'modelmanager' => 'Zoop\Legacy\Store\DocumentManagerFactory',
                    'config' => function($serviceManager) use ($server, $database, $username, $password) {
                        $this->createMongoDbConfig($server, $database, $username, $password);
                        return $this->getMongoDbConfig();
                    }
                ]
            ]
```

So I don't need to create my own service manager. :)

**Comment by superdweebie** [comment]
Hi @crimsonronin. The intention is that you write your own new factory and replace the really basic one that comes with shard. The factory can get the config from where ever it wants. The reason I haven't added configuration for the document manager into shard is because that is one of the things that zf2 doctrine-module does. zf2 shard-module leverages the config and factory provided by doctrine-module to hook everything up for shard to use.
